language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=a4fb63b6996327176e12cf0831e0e08f4631ec26a77fab829bb620971be69318
    - NODE_ENV=test
node_js:
 - "10.15.3"
before_script:
  - npm install add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
 - npm run coveralls
 - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
cache:
  directories:
    - "node_modules"