language: node_js

node_js:
  - "10.15.3"

addons:
  postgresql: "9.6"

cache:
directories:
  - "node_modules"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm run create

script:
  - npm run test 

after_script: 
  - npm run coverage